spring.application.name=travel-desk-api

# =========================================
# APP SETTINGS (DEV)
# =========================================
server.port=8090
spring.profiles.active=dev
# =========================================
# DATASOURCE (LOCAL IDE -> POSTGRES IN DOCKER)
# =========================================
spring.datasource.url=${POSTGRES_DOCKER_URL}
spring.datasource.username=${POSTGRES_DOCKER_USER}
spring.datasource.password=${POSTGRES_DOCKER_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
# =========================================
# JPA / HIBERNATE (DEV)
# =========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# =========================================
# LOGGING
# =========================================
logging.level.org.springframework=info
logging.level.org.hibernate.SQL=warn
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=trace
# =========================================
# Security JWT
# =========================================
jwt.expiration=300000
jwt.refresh-expiration=1800000
jwt.secret_key=${SECRET_KEY}
# =========================================
# Exchange API
# =========================================
FREE_CURRENCY_APIKEY=${FREE_CURRENCY_APIKEY}