spring.application.name=travel-desk-api

spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# Security JWT
jwt.expiration=1800000
jwt.refresh-expiration=1800000
jwt.secret_key=${JWT_SECRET_KEY:${SECRET_KEY}}

# Exchange API
FREE_CURRENCY_APIKEY=${FREE_CURRENCY_APIKEY:}

# Shared datasource defaults
spring.datasource.driver-class-name=org.postgresql.Driver

# HikariCP
spring.datasource.hikari.initialization-fail-timeout=0
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.leak-detection-threshold=0